// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPVHJ17FAvEwiukY_fd8eGcefMPdyXc8',
    appId: '1:214065685114:web:7de3838e8239a5ad5191c3',
    messagingSenderId: '214065685114',
    projectId: 'pagtambong',
    authDomain: 'pagtambong.firebaseapp.com',
    storageBucket: 'pagtambong.firebasestorage.app',
    measurementId: 'G-JBNGS5D4Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_c2CLI_CHHSUDuPvHr8bw9069c9vqA5w',
    appId: '1:214065685114:android:2dbf75b1317e9c335191c3',
    messagingSenderId: '214065685114',
    projectId: 'pagtambong',
    storageBucket: 'pagtambong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqL0SLrOpN_kKsaN-Gq35hRwdJvE3Vcqk',
    appId: '1:214065685114:ios:5a77f2f2cb4406c35191c3',
    messagingSenderId: '214065685114',
    projectId: 'pagtambong',
    storageBucket: 'pagtambong.firebasestorage.app',
    iosBundleId: 'com.example.pagtambongAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqL0SLrOpN_kKsaN-Gq35hRwdJvE3Vcqk',
    appId: '1:214065685114:ios:5a77f2f2cb4406c35191c3',
    messagingSenderId: '214065685114',
    projectId: 'pagtambong',
    storageBucket: 'pagtambong.firebasestorage.app',
    iosBundleId: 'com.example.pagtambongAttendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsPVHJ17FAvEwiukY_fd8eGcefMPdyXc8',
    appId: '1:214065685114:web:be4fe87d7002c94f5191c3',
    messagingSenderId: '214065685114',
    projectId: 'pagtambong',
    authDomain: 'pagtambong.firebaseapp.com',
    storageBucket: 'pagtambong.firebasestorage.app',
    measurementId: 'G-D51DLEBH78',
  );
}
